[project]
description = "Rick Osborne's collection of voting-related utilities."
name = "rickosborne_vote"
readme = "README.md"
requires-python = ">=3.14"
dynamic = ["version"]
license = "CC-BY-NC-SA-4.0"
dependencies = []

[project.urls]
Homepage = "https://github.com/rickosborne/PyRick"
Repository = "https://github.com/rickosborne/PyRick.git"
